### ISSUE TITLE
wrong URL in addon.xml

### ISSUE THREAD

**Issue by dmnc-net** [xbmc-kodi-cz/skin.estuary.stream-cinema.leia#2]
https://github.com/xbmc-kodi-cz/skin.estuary.stream-cinema.leia/blob/c316d3fc7fd8cee0eecdc192884e42cd251fd9bf/addon.xml#L39
should be
```xml
<source>https://github.com/xbmc-kodi-cz/skin.estuary.stream-cinema.leia/</source>
```

**Comment by saxel-cz** [comment]
URL fixed.
